//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guest_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub guest_id: i32,
    pub list: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guest::Entity",
        from = "Column::GuestId",
        to = "super::guest::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Guest,
}

impl Related<super::guest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
