//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guest")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub unique_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::guest_history::Entity")]
    GuestHistory,
    #[sea_orm(has_many = "super::guest_portrait::Entity")]
    GuestPortrait,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
}

impl Related<super::guest_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuestHistory.def()
    }
}

impl Related<super::guest_portrait::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuestPortrait.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
