//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod category_parfumery;
pub mod goods_list;
pub mod guest;
pub mod guest_history;
pub mod parfumery_brand;
pub mod parfumery_class;
pub mod parfumery_seasonality;
pub mod parfumery_volume;
pub mod roles;
pub mod sessions;
pub mod user_history;
pub mod user_info;
pub mod user_logs;
pub mod user_roles;
pub mod users;
