//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "parfumery_seasonality")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub seasonality: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::category_parfumery::Entity")]
    CategoryParfumery,
}

impl Related<super::category_parfumery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryParfumery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
