//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::category_parfumery::Entity as CategoryParfumery;
pub use super::goods_list::Entity as GoodsList;
pub use super::guest::Entity as Guest;
pub use super::guest_history::Entity as GuestHistory;
pub use super::parfumery_brand::Entity as ParfumeryBrand;
pub use super::parfumery_class::Entity as ParfumeryClass;
pub use super::parfumery_seasonality::Entity as ParfumerySeasonality;
pub use super::parfumery_volume::Entity as ParfumeryVolume;
pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::user_history::Entity as UserHistory;
pub use super::user_info::Entity as UserInfo;
pub use super::user_logs::Entity as UserLogs;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
