//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "search_goods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub goods_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category_parfumery::Entity",
        from = "Column::GoodsId",
        to = "super::category_parfumery::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CategoryParfumery,
}

impl Related<super::category_parfumery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryParfumery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
